### ISSUE TITLE
whatanime.ga has moved to trace.moe

### ISSUE THREAD

**Issue by soruly** [anysz/Image2Anime#2]
Hello, I'm (was) the owner of whatanime.ga
A few days ago, the .ga domain was taken down by freenom T_T,
so the site has moved to https://trace.moe
if you are still actively supporting this project, please update the URL, thank you m(_ _;)m
The new API document can be found here:
https://soruly.github.io/trace.moe/

**Comment by ii64** [comment]
Ok thanks for the information 😀 — Going to update it to latest (may port it to nodejs too 😌)
