### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by ghost** [anysz/Image2Anime#5]
When i try to install the package
python3 setup.py 
install                                        
Traceback (most recent call last):             
  File "setup.py", line 5, in <module>         
    import Image2Anime                         
  File "/root/image2anime/Image2Anime/__init__.
py", line 6, in <module>                       
    from .main import Search                   
  File "/root/image2anime/Image2Anime/main.py",
 line 3, in <module>                           
    from . import utils                        
  File "/root/image2anime/Image2Anime/utils.py"
, line 46                                      
    print(f'File Size: {contentlength/1024/1024
} MB')                                         
                                               
    ^                                          
SyntaxError: invalid syntax

Then i remove f

python3 setup.py 
install                                        
Traceback (most recent call last):             
  File "setup.py", line 5, in <module>         
    import Image2Anime                         
  File "/root/image2anime/Image2Anime/__init__.
py", line 6, in <module>                       
    from .main import Search                   
  File "/root/image2anime/Image2Anime/main.py",
 line 4, in <module>                           
    from . import models                       
  File "/root/image2anime/Image2Anime/models.py
", line 153                                    
    self.video_preview = config.host['main'] + 
f'/{self.anilist_id}/{utils.urlencode(self.file
)}?' + utils.urlencode({

I remove f again

It works, but Result is not valid :3 

All results: SearchResult(limit=9, quota=148, C
acheHit=False, RawDocsSearchTime=94164766792764
, quota_ttl=86287, RawDocsCount=63106846, limit
_ttl=60, ReRankSearchTime=7718423521559, scenes
=[AnimeScene(title='フェアリーテイル', title_na
tive='フェアリーテイル', title_english='Fairy T
ail', diff=None, file=None, video_preview='http
s://trace.moe/{self.anilist_id}/{utils.urlencod
e(self.file)}?end=None&token=None&start=None', 
token=None, anilist_id=6702, expires=None, titl
e_chinese='Fairy Tail', is_adult=False, t=None,
 end=None, i=None, to=1012.17, token_thumb='5nF
Gnhln2t8c7YqWf9BP8A', start=None, episode=166, 
from_=1012.17, thumbnail_preview='https://trace
.moe/thumbnail.php?token=5nFGnhln2t8c7YqWf9BP8A
&anilist_id=6702&t=None&file=None', title_romaj
i='Fairy Tail'), AnimeScene(title='Charlotte(シ
ャーロット)', title_native='Charlotte(シャーロ 
ット)', title_english='Charlotte', diff=None, f
ile=None, video_preview='https://trace.moe/{sel
f.anilist_id}/{utils.urlencode(self.file)}?end=
None&token=None&start=None', token=None, anilis
t_id=20997, expires=None, title_chinese='Charlo
tte', is_adult=False, t=None, end=None, i=None,
 to=417.58, token_thumb='TzL-uqgECaLP_MlGVB29Ow
', start=None, episode=1, from_=417.33, thumbna
il_preview='https://trace.moe/thumbnail.php?tok
en=TzL-uqgECaLP_MlGVB29Ow&anilist_id=20997&t=No
ne&file=None', title_romaji='Charlotte'), Anime
Scene(title='Charlotte(シャーロット)', title_na
tive='Charlotte(シャーロット)', title_english='
Charlotte', diff=None, file=None, video_preview
='https://trace.moe/{self.anilist_id}/{utils.ur
lencode(self.file)}?end=None&token=None&start=N
one', token=None, anilist_id=20997,

**Comment by ii64** [comment]
[![Supported python versions: 3.6](https://img.shields.io/badge/python-3.6-green.svg "Supported python versions: 3.6")](https://www.python.org/download/releases/3.6/)

Sorry but it seems you trying to install with python that not support f-string, i also put that mark on README please consider to read it before doing anything, will adding the python version checker on setup.py soon so ppl will get noticed. may i know what's your Python version?
